version: "3.9"
services:
    db:
        image: postgres:latest
        volumes:
            - ./db-data/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=d88hk73hm5jqgj
            - POSTGRES_USER=jvfcxqlngmjtvz
            - POSTGRES_HOST_AUTH_METHOD=trust
            - POSTGRES_HOST=ec2-23-22-191-232.compute-1.amazonaws.com
        ports:
            - "5432:5432"
    migration:
        build: .
        environment:
            - FLASK_ENV:development
        command: flask db upgrade
        depends_on:
            - db
    web:
        build: .
        ports:
        - "5000:5000"
        volumes:
        - .:/app
        environment:
            - FLASK_ENV:development
        links: 
            - db:restapi.local
        depends_on:
            - db  
        entrypoint: ["python", "manage.py","runserver"]

