version: "3.9"
services:
    db:
        image: postgres:latest
        volumes:
            - ./db-data/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=d1oemhgks0bjve
            - POSTGRES_USER=lvpuyaiptcupkp
            - POSTGRES_HOST_AUTH_METHOD=trust
            - POSTGRES_HOST=ec2-54-228-139-34.eu-west-1.compute.amazonaws.com
        ports:
            - "5433:5432"
    web:
        build: .
        ports:
        - "5000:5000"
        volumes:
        - .:/app
        environment:
            - FLASK_ENV:development
        links: 
            - db:restapi.local
        depends_on:
            - db  
        entrypoint: ["python", "manage.py","runserver"]

