"""empty message

Revision ID: c5f42ae2e5ea
Revises: 
Create Date: 2021-05-06 14:48:30.576907

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5f42ae2e5ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finance')
    op.drop_table('calendar')
    op.drop_table('policy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy',
    sa.Column('policy_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('subscription_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('policy_start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('policy_end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('underwriter', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('policy_id', name='policy_pkey')
    )
    op.create_table('calendar',
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('month_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('month_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('day_of_month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('day_of_week', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('year_month', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('date', name='calendar_pkey')
    )
    op.create_table('finance',
    sa.Column('finance_transaction_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('policy_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('premium', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ipt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('finance_transaction_id', name='finance_pkey')
    )
    # ### end Alembic commands ###
